export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const ALL_POSTS = 'ALL_POSTS'
export const ADD_POST = 'ADD_POST'
export const EDIT_POST = 'EDIT_POST'
export const VOTE_POST = 'VOTE_POST'
export const ALL_COMMENTS = 'ALL_COMMENTS'
export const THROW_ERROR = 'THROW_ERROR'